### PR TITLE
removed cf cli installation

### PR DESCRIPTION
**Pull request by Tomcli**
Apparently CF CLI is no longer a prerequisite for BX CLI. So, I removed the install CF CLI part. I will use the pull request Travis build to verify is CF CLI is necessary or not.

### CODE REVIEW

**Comment by Tomcli** [comment]
hmmm apparently the user and password is not accessible in the pull request build

**Comment by animeshsingh** [comment]
Going to do recheck?

**Comment by Tomcli** [comment]
I think pull request can't access any Travis Environment Variables because of security.

**Comment by Tomcli** [comment]
https://travis-ci.org/Tomcli/container-journey-template

Here's my Travis build on my own repo, it looks fine without cf cli. You can check out the logs.

**Pull request merged**
